### ISSUE TITLE
Panic when a directory is missing

### ISSUE THREAD

**Issue by GabrielMajeri** [matthiaskrgr/cargo-cache#9]
I first cleared all my caches by running `cargo cache --remove-dirs all`.
Then I ran the command `cargo cache --top-cache-items 10` to check everything was in order, but I got a panic:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:983:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:477
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   4: rust_begin_unwind
             at libstd/panicking.rs:326
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
   7: cargo_cache::library::get_top_crates
   8: cargo_cache::main
   9: std::rt::lang_start::{{closure}}
  10: main
  11: __libc_start_main
  12: _start
```

The tool should probably check for missing directories and simply ignore them if they don't exist (treat them as if they're empty).

**Comment by matthiaskrgr** [comment]
Oh woops, yeah, this totally sounds like something I probably didn't think of :D

**Comment by matthiaskrgr** [comment]
Should be fixed in latest git, let me know if you find anything else that is messed up!
